### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by TokreN** [raskitoma/pulse-staking-dashboard#5]
Hi,

Got this error, do you have any idea ? I disabled my ufw, reboot, nothing is listening on this port, i tried with prysm, same error too, on mainnet on ubuntu 22.04 like you, on hetzner server, thanks !

![image](https://github.com/raskitoma/pulse-staking-dashboard/assets/79423527/f40032cc-012a-471f-b3ad-3ce4395fbdb1)

**Comment by raskitoma** [comment]
Hi, you need to check if your node has the following:

- If you are using docker, you must have correct network settings (container must have internet access or network access to the nodes: execution/consensus/validator)
- Required ports opened
- Metrics enable on all stuff (execution, consensus and validator)

The message means you have no connection.  Last time I found that error was because I have not setup correctly my docker container network settings.

Let me know if this helps you.

**Comment by raskitoma** [comment]
Since there's no updates, I will asume it was an connection error.
